# Generated by Django 6.0 on 2025-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='contato',
            name='turma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma/Série'),
        ),
    ]
